import {BASE_URL} from "@src/domain/constants"

export const GROUP_USER = {
  ACTION_TYPES: {
    GET_PAGING_BY_PRODUCT_CODE: 'GROUP_USER/GET_PAGING_BY_PRODUCT_CODE',
    GET_LIST_BOX_BY_PRODUCT_CODE: 'GROUP_USER/GET_LIST_BOX_BY_PRODUCT_CODE',
    ADD_BY_PRODUCT_CODE: 'GROUP_USER/ADD_USER_GROUP_USER_BY_PRODUCT_CODE',
    GET_PAGING: 'GROUP_USER/GET_PAGING',
    GET_LIST_BOX: 'GROUP_USER/GET_LIST_BOX',
    GET_PAGING_USERS_GROUP_USER: 'GROUP_USER/GET_PAGING_USERS_GROUP_USER',
    ADD: 'GROUP_USER/ADD',
    ADD_USER_GROUP_USER: 'GROUP_USER/ADD_USER_GROUP_USER',
    REMOVE_USER_GROUP_USER: 'GROUP_USER/REMOVE_USER_GROUP_USER',
    GET_PAGING_USERS: 'GROUP_USER/GET_USER_GROUP_USER',
    UPDATE: 'GROUP_USER/UPDATE',
    DELETE: 'GROUP_USER/DELETE'
  },
  URL_API: {
    GET_PAGING_BY_PRODUCT_CODE_API: `${BASE_URL}/api/roles/paging-by-product-code`,
    GET_LISTBOX_BY_PRODUCT_CODE_API: `${BASE_URL}/api/roles/get-listbox-by-product-code`,
    ADD_BY_PRODUCT_CODE_API: `${BASE_URL}/api/roles/add-by-product-code`,
    GET_PAGING_API: `${BASE_URL}/api/roles/paging`,
    GET_LISTBOX_API: `${BASE_URL}/api/roles/get-listbox`,
    GET_PAGING_USERS_GROUP_USER_API: `${BASE_URL}/api/roles/paging-users-role`,
    ADD_API: `${BASE_URL}/api/roles/add`,
    ADD_USERS_GROUP_USER_API: `${BASE_URL}/api/roles/add-users-role`,
    REMOVE_USER_GROUP_USER_API: `${BASE_URL}/api/roles/remove-user-role`,
    GET_PAGING_USERS_API: `${BASE_URL}/api/roles/paging-users-add`,
    UPDATE_API: `${BASE_URL}/api/roles/edit`,
    DELETE_API: `${BASE_URL}/api/roles/delete`
  }
}

export const PERMISSION = {
  ACTION_TYPES: {
    GET_PERMISSION_GROUP_USER_BY_PRODUCT: 'PERMISSION/GET_PERMISSION_GROUP_USER_BY_PRODUCT',
    GET_PERMISSION_USER_BY_PRODUCT: 'PERMISSION/GET_PERMISSION_USER_BY_PRODUCT',
    GET_TREE_PERMISSION: 'PERMISSION/GET_TREE_PERMISSION',
    GET_TREE_RESOURCE_PERMISSION: 'PERMISSION/GET_TREE_RESOURCE_PERMISSION',
    GET_PERMISSION_GROUP_USER: 'PERMISSION/GET_PERMISSION_GROUP_USER',
    GET_PAGING_GROUP_USERS_FOR_ADD: 'PERMISSION/GET_PAGING_GROUP_USERS_FOR_ADD',
    GET_PAGING_GROUP_USERS_FOR_ADD_BY_PRODUCT: 'PERMISSION/GET_PAGING_GROUP_USERS_FOR_ADD_BY_PRODUCT',
    GET_PAGING_USERS_FOR_ADD: 'PERMISSION/GET_PAGING_USERS_FOR_ADD',
    GET_PAGING_USERS_FOR_ADD_BY_PRODUCT: 'PERMISSION/GET_PAGING_USERS_FOR_ADD_BY_PRODUCT',
    GET_PERMISSION_FUNCTION: 'PERMISSION/GET_PERMISSION_FUNCTION',
    GET_PERMISSION_USER: 'PERMISSION/GET_PERMISSION_USER',
    ADD_PERMISSION_GROUP_USER: 'PERMISSION/ADD_PERMISSION_GROUP_USER',
    DELETE_PERMISSION_GROUP_USER: 'PERMISSION/DELETE_PERMISSION_GROUP_USER',
    ADD_PERMISSION_USER: 'PERMISSION/ADD_PERMISSION_USER',
    DELETE_PERMISSION_USER: 'PERMISSION/DELETE_PERMISSION_USER'
  },
  URL_API: {
    GET_PERMISSION_GROUP_USER_BY_PRODUCT_API: `${BASE_URL}/api/privileges/get-permission-role-by-product-code`,
    GET_PERMISSION_USER_BY_PRODUCT_API: `${BASE_URL}/api/privileges/get-permission-user-by-product-code`,
    GET_TREE_PERMISSION_API: `${BASE_URL}/api/resource/get-tree-permission`,
    GET_TREE_RESOURCE_PERMISSION_API: `${BASE_URL}/api/privileges/get-tree-permission-info`,
    GET_PERMISSION_GROUP_USER_API: `${BASE_URL}/api/privileges/get-permission-role`,
    GET_PAGING_GROUP_USERS_FOR_ADD_API: `${BASE_URL}/api/privileges/get-roles-for-add`,
    GET_PAGING_GROUP_USERS_FOR_ADD_BY_PRODUCT_API: `${BASE_URL}/api/privileges/get-roles-for-add-by-product`,
    GET_PAGING_USERS_FOR_ADD_API: `${BASE_URL}/api/privileges/get-users-for-add`,
    GET_PAGING_USERS_FOR_ADD_BY_PRODUCT_API: `${BASE_URL}/api/privileges/get-users-for-add-by-product`,
    GET_PERMISSION_FUNCTION_API: `${BASE_URL}/api/privileges/get-permission-function`,
    GET_PERMISSION_USER_API: `${BASE_URL}/api/privileges/get-permission-user`,
    ADD_PERMISSION_GROUP_USER_API: `${BASE_URL}/api/privileges/add-permission-role`,
    DELETE_PERMISSION_GROUP_USER_API: `${BASE_URL}/api/privileges/delete-permission-role`,
    ADD_PERMISSION_USER_API: `${BASE_URL}/api/privileges/add-permission-user`,
    DELETE_PERMISSION_USER_API: `${BASE_URL}/api/privileges/delete-permission-user`
  }
}

export const USER = {
  ACTION_TYPES: {
    GET_PAGING_BY_PRODUCT_ID: 'SYSTEM_USER/GET_PAGING_BY_PRODUCT_ID',
    GET_USERS_BY_PRODUCT_ID: 'SYSTEM_USER/GET_USERS_BY_PRODUCT_ID',
    ADD_BY_PRODUCT_ID: 'SYSTEM_USER/ADD_BY_PRODUCT_ID',
    GET_PAGING: 'SYSTEM_USER/GET_PAGING',
    GET_USERS: 'SYSTEM_USER/GET_USERS',
    ADD: 'SYSTEM_USER/ADD',
    UPDATE: 'SYSTEM_USER/UPDATE',
    DELETE: 'SYSTEM_USER/DELETE'
  },
  URL_API: {
    GET_PAGING_BY_PRODUCT_ID: `${BASE_URL}/api/productuser/paging-by-product-id`,
    GET_USERS_BY_PRODUCT_ID: `${BASE_URL}/api/productuser/get-users-add-by-product-id`,
    ADD_BY_PRODUCT_ID: `${BASE_URL}/api/productuser/add-by-product-id`,
    GET_PAGING_API: `${BASE_URL}/api/productuser/paging`,
    GET_USERS_API: `${BASE_URL}/api/productuser/get-users-add`,
    ADD_API: `${BASE_URL}/api/productuser/add`,
    UPDATE_API: `${BASE_URL}/api/productuser/edit`,
    DELETE_API: `${BASE_URL}/api/productuser/delete`
  }
}